# Site settings
title: Rapid Programmer - Get Tasks Done
description: >
  Tech blog by Jarno Tuovinen
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rapidprogrammer.com"
snapchat_username: mrtuovinen
twitter_username: mrtuovinen
linkedin_username: jarnotuovinen
github_username: spedepekka
youtube_username: spedepekka

markdown: kramdown
