title: Rapid Programmer - Get Tasks Done
description: >
  Tech blog by Jarno Tuovinen
baseurl: ""
url: "http://rapidprogrammer.com"

markdown: kramdown
gems:
  - jekyll-sitemap

snapchat_username: mrtuovinen
twitter_username: mrtuovinen
linkedin_username: jarnotuovinen
github_username: spedepekka
youtube_username: spedepekka
